# Generated by Django 3.0.1 on 2020-01-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='名前')),
                ('amount', models.IntegerField(default=0)),
                ('registered_date', models.DateField(null=True, verbose_name='日時')),
                ('category', models.CharField(choices=[('給与所得', '給与所得'), ('食費', '食費'), ('Water Bills', '水道代'), ('ガス代', 'ガス代'), ('電気代', '電気代'), ('携帯代', '携帯代'), ('ガチャ課金', 'ガチャ課金'), ('通信費', '通信費'), ('交際費', '交際費'), ('交通費', '交通費'), ('家賃', '家賃'), ('その他', 'その他')], max_length=100, verbose_name='カテゴリ')),
                ('balance_type', models.CharField(choices=[('収入', '収入'), ('支出', '支出')], max_length=20, verbose_name='収支タイプ')),
            ],
        ),
    ]
