# Generated by Django 3.0 on 2020-01-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='category',
            field=models.CharField(choices=[('給与所得', '給与所得'), ('食費', '食費'), ('水道代', '水道代'), ('ガス代', 'ガス代'), ('電気代', '電気代'), ('携帯代', '携帯代'), ('ガチャ課金', 'ガチャ課金'), ('通信費', '通信費'), ('交際費', '交際費'), ('交通費', '交通費'), ('家賃', '家賃'), ('その他', 'その他')], max_length=100, verbose_name='カテゴリ'),
        ),
    ]
